"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const readingAnnotations = {
    // ===== 201906 第一套 =====
    // 选词填空 2019061
    1779441964372: {
        vocab: {
            innovation: 'n. 创新',
            vehicles: 'n. 车辆',
            lawmakers: 'n. 立法者',
            legislation: 'n. 法律，法规',
            dominance: 'n. 主导地位',
            substantial: 'adj. 重大的',
            manufacturer: 'n. 制造商',
            commercial: 'adj. 商业的',
            restrictive: 'adj. 限制性的',
        },
        qHint: {
            '26': '助动词has后接过去分词，from...to...表迁移 → migrated 迁移',
            '27': '不定冠词a后接名词，a bid to do = 为做某事而作的努力',
            '28': 'introduced后接名词作宾语，立法者提出法案 → legislation',
            '29': '所有格Michigan\'s后接名词，在汽车研发方面的主导地位 → dominance',
            '30': 'desire to do，不定式后接动词原形，取代领导地位 → replace',
            '31': 'the lead后接表示身份的名词，四项法案的主要发起人 → sponsor',
            '32': 'would后接动词原形，法案通过意味着重大更新 → represent 意味着',
            '33': 'on-demand后接名词，按需的车队 → fleets',
            '34': 'In后接名词构成状语，与上文形成对比 → contrast',
            '35': '比较级far more后接形容词修饰rules → restrictive 限制性的',
        },
        translation: '在过去的十年间，美国汽车创新中心已经搬到了2000英里之外。它已经从底特律迁到硅谷，在那里，无人驾驶汽车正在焕发生机。为了让无人驾驶汽车的生产重返底特律，密歇根州的立法者已经提出法案。密歇根州在汽车研发领域的主导地位受到了几个州和国家的威胁。如果这四项法案都以书面形式通过了，那么它们将意味着密歇根州2013年一项法律的重大更新。密歇根州的立法者希望该州为无人驾驶技术的商业应用做好准备。相比之下，加州则提出了更为严格的规定，禁止无人驾驶技术用于商业用途。',
    },
    // 长篇匹配 2019061
    1779441964374: {
        vocab: {
            centenarians: 'n. 百岁老人',
            longevity: 'n. 长寿',
            inevitable: 'adj. 不可避免的',
            milestones: 'n. 里程碑',
            sabbaticals: 'n. 休假',
            tangible: 'adj. 有形的',
            profound: 'adj. 深刻的',
            transitions: 'n. 转变，过渡',
            vitality: 'n. 活力',
            implications: 'n. 影响，含义',
            commitments: 'n. 承诺，责任',
            demographic: 'adj. 人口的',
            trajectory: 'n. 轨迹',
            assets: 'n. 资产',
            sequences: 'n. 序列，顺序',
        },
        qLocate: {
            '0': 'I段',
            '1': 'G段',
            '2': 'D段',
            '3': 'N段',
            '4': 'A段',
            '5': 'K段',
            '6': 'H段',
            '7': 'F段',
            '8': 'M段',
            '9': 'C段',
        },
        qHint: {
            '0': 'I段：传统的三阶段人生变成多阶段 → 人生会有更多不同职业。',
            '1': 'G段：延长职业能保障经济，但也会耗尽无形资产如活力、友谊。',
            '2': 'D段：1962年50%美国人在21岁前结婚→2014年推迟到29岁，约8年。',
            '3': 'N段：三阶段人生（教育→工作→退休）适用父母祖辈，但今天已不适用。',
            '4': 'A段：到2050年仅美国就有超过100万百岁老人。',
            '5': 'K段：多阶段人生会导致对生活和工作的方式产生深刻变化。',
            '6': 'H段：技术变革速度快，要么技能过时要么行业淘汰，必须不断再投资技能。',
            '7': 'F段：即使经济上能65岁退休，30多年不工作也会伤害认知和情感活力。',
            '8': 'M段：伴随多阶段人生的多样性，年龄和阶段的紧密联系即将结束。',
            '9': 'C段：如果人们活得更长更健康，将不可避免地重新规划工作和生活。',
        },
        translation: '如今，美国有72000名百岁老人。全世界大概有45万。如果目前的趋势继续下去，那么到2050年，仅在美国就有超过100万的百岁老人。可以理解的是，鉴于给相关医疗和养老金带来的挑战，人们不禁担心这会对公共财政带来什么影响。我们的观点是，如果许多人活得更长、健康的时间更长，那么这将不可避免地导致重新规划工作和生活。但变化远不止于此。1962年，50%的美国人在21岁之前结婚。到2014年，这一里程碑已经转移到了29岁。这些转变背后有很多因素，但其中一个因素肯定是年轻人越来越意识到他们将活得更长久。长寿还会推迟退休年龄，但30多年不工作也会对认知和情感活力造成伤害。然而，那并不意味着简单地延长我们的职业生涯是有吸引力的。教育也是如此。如果在童年和成年初期只接受一次教育，将不可能支撑持续60年的职业生涯。传统的三阶段人生似乎将演变为包含多个不同职业的多阶段人生。多阶段的人生将不仅仅导致你管理事业的方式产生深刻变化，也会导致你的生活方式产生深刻变化。伴随这种多样性，年龄和人生阶段的紧密联系即将结束。当前的生活结构、职业道路、教育选择和社会规范与人们日趋长寿的新现实格格不入。',
    },
    // 仔细阅读 2019061 第一篇 - Divorce risk
    1779441964376: {
        vocab: {
            vow: 'n. 誓言，誓约',
            spouse: 'n. 配偶',
            diagnosed: 'v. 诊断',
            struggling: 'v. 挣扎，艰难应对',
            onset: 'n. 发生，开始',
            chronic: 'adj. 慢性的',
            vulnerable: 'adj. 脆弱的',
            marital: 'adj. 婚姻的',
            widowed: 'adj. 丧偶的',
            norms: 'n. 准则，规范',
            caregiving: 'n. 看护，照料',
            prospective: 'adj. 潜在的，未来的',
            policymakers: 'n. 政策制定者',
        },
        qLocate: {
            '0': 'P1',
            '1': 'P4',
            '2': 'P5',
            '3': 'P6',
            '4': 'P8',
        },
        qHint: {
            '0': '文首说誓约承诺"无论生病健康都在一起"，但第二句立刻转折 But... 指出离婚风险上升 → 誓约并不能保证婚姻持久。',
            '1': '定位 P4 末句："more husbands than wives developing serious health problems" → D 选项 "比妻子更容易得重病"。',
            '2': '定位 P5："more likely to get divorced" → 女性病了更容易被离婚。注意区分"丧偶 widowed"和"离婚 divorced"。',
            '3': '定位 P6："Gender norms... may make it more difficult for men to provide care" → 性别准则使得男性更习惯于接受照顾而非提供。',
            '4': '定位 P8 末句："sick ex-wives may need additional care and services" → 对应 C 选项 "给离婚女性提供额外照顾"。',
        },
        translation: '在经典的结婚誓约中，夫妻双方承诺无论生病还是健康都要在一起。但是一项新的研究发现，当上了年纪的夫妻中的妻子而不是丈夫得了严重的疾病时，离婚的风险会上升。"被诊断为健康状况糟糕的已婚妇女也许会发现，她们在与疾病抗争的同时，还承受着离婚的压力。"自从1992年以来，印第安纳大学就2717例婚姻进行了研究。研究人员研究了四种严重的身体疾病的发生对婚姻的影响。总体来说，31%的婚姻在研究期间以离婚告终，其中丈夫比妻子更容易出现严重的健康问题。"我们发现，在面对疾病时，女性更容易遭遇婚姻的破裂。"虽然该研究并没有评估为什么当妻子重病时离婚的可能性更大，但卡拉克提供了一些可能的原因，包括性别准则以及社会对付出关怀的预期。卡拉克认为政策制定者应该意识到疾病和离婚风险之间的关系，给离婚女性提供额外的照顾和服务。',
    },
    // 仔细阅读 2019061 第二篇 - Misnaming
    1779441964377: {
        vocab: {
            sibling: 'n. 兄弟姐妹',
            cognitive: 'adj. 认知的',
            classify: 'v. 分类',
            invariably: 'adv. 总是，不变地',
            resemblance: 'n. 相似',
            conducted: 'v. 实施，进行',
            incidents: 'n. 事件',
            boundaries: 'n. 界限',
            frustrated: 'adj. 沮丧的',
            random: 'adj. 随机的',
        },
        qLocate: {
            '0': 'P1',
            '1': 'P2',
            '2': 'P4',
            '3': 'P5',
            '4': 'P6',
        },
        qHint: {
            '0': '首句 "you probably got upset" → 不高兴，对应 B 选项 Unhappy。',
            '1': 'P2："common cognitive error that has to do with how our memories classify and store familiar names" → 与记忆工作方式有关。',
            '2': 'P4："names shared initial or internal sounds" → 名字发音相似导致叫错。',
            '3': 'P5："people mixed up names within relationship groups" → 错误发生在关系群体内部。',
            '4': 'P6："mothers may call on their children more often than fathers" → 母亲和孩子交流更多。',
        },
        translation: '如果你和大多数孩子一样，当你的母亲叫你的时候误叫成了你兄弟姐妹的名字，你很有可能感到难过。根据研究，叫错生活中最熟悉的人的名字是一种常见的认知错误，与我们的记忆如何归类和储存熟悉的名字有关。该研究并没有考察这个错误是否具有深刻的心理意义，但它告诉我们在同一个关系群体中，叫错名字的情况会发生在名字开头或中间的发音相同的人身上。所有的调查都发现，混淆名字往往存在于某种关系群体内部。研究发现大学生和老年人犯这种错误的概率差不多，男性和女性也差不多。鉴于传统的性别准则，母亲叫孩子名字的次数或许多于父亲。',
    },
    // ===== 201906 第二套 =====
    // 选词填空 2019062 - Killer whales
    1779441964430: {
        vocab: {
            predators: 'n. 食肉动物',
            brutal: 'adj. 残忍的，野蛮的',
            refined: 'adj. 精炼的，完善的',
            literally: 'adv. 字面上，确实',
            acquired: 'adj. 后天习得的',
            instinctive: 'adj. 本能的',
            adaptations: 'n. 适应',
            thrive: 'v. 繁荣，茁壮成长',
            habitats: 'n. 栖息地',
            speculate: 'v. 推测，推断',
        },
        qLocate: {
            '26': 'P1',
            '27': 'P1',
            '28': 'P1',
            '29': 'P2',
            '30': 'P2',
            '31': 'P3',
            '32': 'P3',
            '33': 'P4',
            '34': 'P4',
            '35': 'P4',
        },
        qHint: {
            '26': '最高级the most后接形容词，修饰捕食者 → brutal 残忍的',
            '27': '定冠词the后接名词，符合有文化生物的形象 → image',
            '28': 'highly后接形容词修饰behaviors → refined 精炼的/完善的',
            '29': 'which引导从句修饰colere，字面意思 → literally 字面上',
            '30': 'or连接并列结构，与learnt同义 → acquired 后天习得的',
            '31': 'genetic后接名词，帮助消化利用高脂饮食的适应能力 → adaptations',
            '32': 'allow them to后接动词原形，在寒冷气候中繁衍生息 → thrive',
            '33': 'a range of different后接名词复数，全球不同栖息地 → habitats',
            '34': 'that引导定语从句，帝国从极地延伸到极地 → extends',
            '35': 'leading scientists to后接动词原形，科学家推测 → speculate',
        },
        translation: '仅仅因为它们不会唱歌剧或骑自行车并不意味着动物没有文化。虎鲸就是最好的例证。作为最凶猛的食肉动物之一，虎鲸或许不符合有文化生物的形象。然而，这些海洋巨兽确实表现出各种各样高度完善的行为，这些行为似乎正在推动它们的遗传发展。"文化"一词来自拉丁语，意思是"耕种"。它指的是任何后天习得的、而非本能或天然的东西。就像人类一样，虎鲸已经在全球不同栖息地扎根，不同虎鲸种群必须学习不同的捕猎技术。这反过来对它们的饮食产生了重大影响，引导科学家们推测，学习特定种群捕猎方法的能力可能正在推动这些动物的遗传发展。',
    },
    // 长篇匹配 2019062 - Young adults
    1779441964431: {
        vocab: {
            demographic: 'adj. 人口的',
            attainment: 'n. 成就，达到',
            spouse: 'n. 配偶',
            postponement: 'n. 推迟',
            cohabitation: 'n. 同居',
            trajectory: 'n. 轨迹',
            prevalent: 'adj. 普遍的',
            recession: 'n. 衰退',
            counterparts: 'n. 对应的人/物',
            enrollments: 'n. 入学人数',
        },
        qLocate: {
            '0': 'H段',
            '1': 'E段',
            '2': 'B段',
            '3': 'B段',
            '4': 'K段',
            '5': 'F段',
            '6': 'I段',
            '7': 'H段',
            '8': 'J段',
            '9': 'G段',
        },
        qHint: {
            '0': 'H段：有工作的年轻人比没工作的更不可能住父母家，青年男性就业率下降。',
            '1': 'E段：2014年35%年轻男性住父母家，29%年轻女性住父母家。',
            '2': 'B段：1960年62%已婚/同居→2014年31.6%，大幅下降。',
            '3': 'B段：1960年only one-in-five(20%)住父母家。',
            '4': 'K段：有本科学位的年轻人在劳动力市场表现更好，更容易独立生活。',
            '5': 'F段：年轻女性(16%)比男性(13%)更可能成为单亲家长。',
            '6': 'I段：年轻女性住父母家增加，部分原因与男性劳动力市场结果相关的晚婚。',
            '7': 'H段：青年男性就业率从1960年84%降至2014年71%，收入下降。',
            '8': 'J段：经济大衰退初期大学入学人数扩大，增加了住父母家的年轻人数量。',
            '9': 'G段：晚婚或避免结婚是年轻人住父母家比例上升的首要因素。',
        },
    },
    // 仔细阅读 2019062 第一篇 - Women leaders
    1779441964433: {
        vocab: {
            capable: 'adj. 有能力的',
            corporate: 'adj. 公司的',
            indistinguishable: 'adj. 难以区分的',
            passionate: 'adj. 热情的',
            toughness: 'n. 坚韧',
            interruptions: 'n. 中断',
            counterparts: 'n. 对应的人',
            electorate: 'n. 选民',
            foreseeable: 'adj. 可预见的',
            barrier: 'n. 障碍',
        },
        qLocate: {
            '0': 'P1',
            '1': 'P3',
            '2': 'P4',
            '3': 'P5',
            '4': 'P6',
        },
        qHint: {
            '0': 'P1："women indistinguishable from men on key leadership traits" → 女性和男性一样聪明有创新力。',
            '1': 'P3："career interruptions related to motherhood may make it harder for women to advance" → 家庭责任影响职业发展。',
            '2': 'P4："a double standard... they have to do more than their male counterparts to prove themselves" → 性别偏见是主要因素。',
            '3': 'P5："the public is divided" → 公众对未来是否有更多女性领导持分歧意见。',
            '4': 'P6："73% expect to see a female president in their lifetime" → 期待有女性进入最高领导职位。',
        },
        translation: '根据大多数美国人的看法，女性在成为优秀的政治领袖方面和男性一样有能力。一项新调查显示，大多数美国人发现女性在智力和创新能力等关键领导特质上与男性无法区分。那么为什么在政府和商界顶层女性供不应求呢？经济研究显示，与母职相关的职业中断可能使女性更难在职业上取得进步。但大约四成美国人指出女性在攀登高层时面临双重标准——她们必须比男性同行付出更多来证明自己。因此，公众对于企业界的不平衡是否会改变存在分歧。53%的人认为男性将继续占据更多高管职位，44%的人表示这只是时间问题。美国人在政治方面则不那么怀疑：73%的人期望在有生之年看到一位女性总统。',
    },
    // 仔细阅读 2019062 第二篇 - Height
    1779441964434: {
        vocab: {
            nutrition: 'n. 营养',
            genetics: 'n. 遗传学',
            cardiovascular: 'adj. 心血管的',
            reversed: 'v. 逆转',
            potential: 'n. 潜力',
            implications: 'n. 影响',
            adjustment: 'adj. 调整',
            average: 'n. 平均',
            primarily: 'adv. 主要地',
            productive: 'adj. 有生产力的',
        },
        qLocate: {
            '0': 'P1',
            '1': 'P2',
            '2': 'P3',
            '3': 'P4',
            '4': 'P5',
        },
        qHint: {
            '0': 'P1：全球研究显示大多数国家人的身高在上一世纪明显增长。',
            '1': 'P2："genetics plays a less key role" when averaging over populations → 遗传对个体影响大但对群体影响小。',
            '2': 'P3："Being taller is associated with longer life expectancy" → 更高的人寿命更长。',
            '3': 'P4："the trend has reversed... height decreasing" → 现在比之前几代人更矮。',
            '4': 'P5："strongly influenced by the environment we grew up in" → 确保孩子在理想环境中成长。',
        },
        translation: '在过去一个世纪里，人类的身高增长了，韩国女性的平均身高增长超过20厘米，伊朗男性增长了16.5厘米。一项全球研究调查了1914年至2014年间200个国家18岁青年的平均身高。伦敦帝国理工学院的詹姆斯·本瑟姆说，全球趋势可能主要归因于营养和医疗保健的改善。他补充说遗传对个体的身高有很大影响，但一旦在整个人群中取平均值，遗传的作用就没那么关键了。身高更高的人预期寿命更长，主要是因为身材较高的人死于心血管疾病的风险较低。北非和撒哈拉以南非洲许多国家的趋势令人担忧，近年来乌干达和尼日尔的身高正在下降。本瑟姆认为，全球身高增长趋势有重要影响，人的身高很大程度上受成长环境影响。如果我们给孩子最好的人生起点，他们将在未来几十年更健康、更富有生产力。',
    },
};
exports.default = readingAnnotations;
